spring.application.name=task-tracker

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# OpenMapper
openmapper.model.packagesToScan=com.example.tasktracker.model
openmapper.dao.packagesToScan=com.example.tasktracker.dao
openmapper.fsql.path=queries
openmapper.sql.tracing.queries.enabled=true
openmapper.logging.enabled=true
openmapper.input.wrapping.enabled=true

# Server
server.port=8080
